/** Indian city / metro list used for location autocomplete suggestions. */
export const INDIA_LOCATIONS: string[] = [
  "Bengaluru, Karnataka",
  "Mumbai, Maharashtra",
  "Delhi, Delhi",
  "New Delhi, Delhi",
  "Gurugram, Haryana",
  "Noida, Uttar Pradesh",
  "Greater Noida, Uttar Pradesh",
  "Faridabad, Haryana",
  "Ghaziabad, Uttar Pradesh",
  "Hyderabad, Telangana",
  "Chennai, Tamil Nadu",
  "Pune, Maharashtra",
  "Kolkata, West Bengal",
  "Ahmedabad, Gujarat",
  "Surat, Gujarat",
  "Vadodara, Gujarat",
  "Rajkot, Gujarat",
  "Gandhinagar, Gujarat",
  "Jaipur, Rajasthan",
  "Udaipur, Rajasthan",
  "Jodhpur, Rajasthan",
  "Kota, Rajasthan",
  "Lucknow, Uttar Pradesh",
  "Kanpur, Uttar Pradesh",
  "Varanasi, Uttar Pradesh",
  "Prayagraj, Uttar Pradesh",
  "Agra, Uttar Pradesh",
  "Meerut, Uttar Pradesh",
  "Indore, Madhya Pradesh",
  "Bhopal, Madhya Pradesh",
  "Gwalior, Madhya Pradesh",
  "Jabalpur, Madhya Pradesh",
  "Nagpur, Maharashtra",
  "Nashik, Maharashtra",
  "Aurangabad, Maharashtra",
  "Thane, Maharashtra",
  "Navi Mumbai, Maharashtra",
  "Kolhapur, Maharashtra",
  "Chandigarh, Chandigarh",
  "Ludhiana, Punjab",
  "Amritsar, Punjab",
  "Jalandhar, Punjab",
  "Mohali, Punjab",
  "Patiala, Punjab",
  "Dehradun, Uttarakhand",
  "Haridwar, Uttarakhand",
  "Shimla, Himachal Pradesh",
  "Jammu, Jammu & Kashmir",
  "Srinagar, Jammu & Kashmir",
  "Patna, Bihar",
  "Gaya, Bihar",
  "Ranchi, Jharkhand",
  "Jamshedpur, Jharkhand",
  "Dhanbad, Jharkhand",
  "Bhubaneswar, Odisha",
  "Cuttack, Odisha",
  "Rourkela, Odisha",
  "Raipur, Chhattisgarh",
  "Bhilai, Chhattisgarh",
  "Guwahati, Assam",
  "Dibrugarh, Assam",
  "Silchar, Assam",
  "Shillong, Meghalaya",
  "Imphal, Manipur",
  "Aizawl, Mizoram",
  "Agartala, Tripura",
  "Kohima, Nagaland",
  "Gangtok, Sikkim",
  "Itanagar, Arunachal Pradesh",
  "Mysuru, Karnataka",
  "Mangaluru, Karnataka",
  "Hubballi, Karnataka",
  "Belagavi, Karnataka",
  "Udupi, Karnataka",
  "Coimbatore, Tamil Nadu",
  "Madurai, Tamil Nadu",
  "Tiruchirappalli, Tamil Nadu",
  "Salem, Tamil Nadu",
  "Tirunelveli, Tamil Nadu",
  "Erode, Tamil Nadu",
  "Vellore, Tamil Nadu",
  "Puducherry, Puducherry",
  "Kochi, Kerala",
  "Thiruvananthapuram, Kerala",
  "Kozhikode, Kerala",
  "Thrissur, Kerala",
  "Kannur, Kerala",
  "Kollam, Kerala",
  "Visakhapatnam, Andhra Pradesh",
  "Vijayawada, Andhra Pradesh",
  "Guntur, Andhra Pradesh",
  "Tirupati, Andhra Pradesh",
  "Nellore, Andhra Pradesh",
  "Warangal, Telangana",
  "Karimnagar, Telangana",
  "Siliguri, West Bengal",
  "Durgapur, West Bengal",
  "Asansol, West Bengal",
  "Howrah, West Bengal",
  "Goa, Goa",
  "Panaji, Goa",
  "Remote, India",
  "Dubai, UAE",
  "Singapore",
  "London, UK",
  "San Francisco, USA",
  "New York, USA",
];

export function suggestLocations(query: string, limit = 6): string[] {
  const q = query.trim().toLowerCase();
  if (!q) return INDIA_LOCATIONS.slice(0, limit);
  const starts: string[] = [];
  const contains: string[] = [];
  for (const loc of INDIA_LOCATIONS) {
    const l = loc.toLowerCase();
    if (l.startsWith(q)) starts.push(loc);
    else if (l.includes(q)) contains.push(loc);
    if (starts.length >= limit) break;
  }
  return [...starts, ...contains].slice(0, limit);
}
