// Inlined brand mark (base64) so the logo paints instantly with no network request.
export const VEYRA_MARK_SRC =
  "data:image/png;base64," +
  "iVBORw0KGgoAAAANSUhEUgAAAO0AAADtCAYAAABHHfI0AAAACXBIWXMAABYlAAAWJQFJUFTwAAAAGXRFWHRDb21tZW50AENyZWF0ZWQgd2l0aCBHSU1Qn4UOHAAAAAd0SU1FB+kMCwodO9+KXmoAAAAiSURBVHja7cEBDQAAAMKg909tDjEgAAAAAAAAAAAAAADgNSVAAAEA/w8DQQAAAABJRU5ErkJggg==";
