/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MatchesRouteImport } from './routes/matches'
import { Route as InvestorFeedRouteImport } from './routes/investor-feed'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InboxIndexRouteImport } from './routes/inbox.index'
import { Route as ForumIndexRouteImport } from './routes/forum.index'
import { Route as ProfileMeRouteImport } from './routes/profile.me'
import { Route as ProfileFounderIdRouteImport } from './routes/profile.$founderId'
import { Route as InboxConversationIdRouteImport } from './routes/inbox.$conversationId'
import { Route as ForumPostIdRouteImport } from './routes/forum.$postId'
import { Route as AuthSignupRouteImport } from './routes/auth.signup'
import { Route as AuthLoginRouteImport } from './routes/auth.login'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesRoute = MatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestorFeedRoute = InvestorFeedRouteImport.update({
  id: '/investor-feed',
  path: '/investor-feed',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxIndexRoute = InboxIndexRouteImport.update({
  id: '/inbox/',
  path: '/inbox/',
  getParentRoute: () => rootRouteImport,
} as any)
const ForumIndexRoute = ForumIndexRouteImport.update({
  id: '/forum/',
  path: '/forum/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileMeRoute = ProfileMeRouteImport.update({
  id: '/profile/me',
  path: '/profile/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileFounderIdRoute = ProfileFounderIdRouteImport.update({
  id: '/profile/$founderId',
  path: '/profile/$founderId',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxConversationIdRoute = InboxConversationIdRouteImport.update({
  id: '/inbox/$conversationId',
  path: '/inbox/$conversationId',
  getParentRoute: () => rootRouteImport,
} as any)
const ForumPostIdRoute = ForumPostIdRouteImport.update({
  id: '/forum/$postId',
  path: '/forum/$postId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/discover': typeof DiscoverRoute
  '/investor-feed': typeof InvestorFeedRoute
  '/matches': typeof MatchesRoute
  '/onboarding': typeof OnboardingRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/forum/$postId': typeof ForumPostIdRoute
  '/inbox/$conversationId': typeof InboxConversationIdRoute
  '/profile/$founderId': typeof ProfileFounderIdRoute
  '/profile/me': typeof ProfileMeRoute
  '/forum/': typeof ForumIndexRoute
  '/inbox/': typeof InboxIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/discover': typeof DiscoverRoute
  '/investor-feed': typeof InvestorFeedRoute
  '/matches': typeof MatchesRoute
  '/onboarding': typeof OnboardingRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/forum/$postId': typeof ForumPostIdRoute
  '/inbox/$conversationId': typeof InboxConversationIdRoute
  '/profile/$founderId': typeof ProfileFounderIdRoute
  '/profile/me': typeof ProfileMeRoute
  '/forum': typeof ForumIndexRoute
  '/inbox': typeof InboxIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/discover': typeof DiscoverRoute
  '/investor-feed': typeof InvestorFeedRoute
  '/matches': typeof MatchesRoute
  '/onboarding': typeof OnboardingRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/forum/$postId': typeof ForumPostIdRoute
  '/inbox/$conversationId': typeof InboxConversationIdRoute
  '/profile/$founderId': typeof ProfileFounderIdRoute
  '/profile/me': typeof ProfileMeRoute
  '/forum/': typeof ForumIndexRoute
  '/inbox/': typeof InboxIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/discover'
    | '/investor-feed'
    | '/matches'
    | '/onboarding'
    | '/auth/login'
    | '/auth/signup'
    | '/forum/$postId'
    | '/inbox/$conversationId'
    | '/profile/$founderId'
    | '/profile/me'
    | '/forum/'
    | '/inbox/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/discover'
    | '/investor-feed'
    | '/matches'
    | '/onboarding'
    | '/auth/login'
    | '/auth/signup'
    | '/forum/$postId'
    | '/inbox/$conversationId'
    | '/profile/$founderId'
    | '/profile/me'
    | '/forum'
    | '/inbox'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/discover'
    | '/investor-feed'
    | '/matches'
    | '/onboarding'
    | '/auth/login'
    | '/auth/signup'
    | '/forum/$postId'
    | '/inbox/$conversationId'
    | '/profile/$founderId'
    | '/profile/me'
    | '/forum/'
    | '/inbox/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  DiscoverRoute: typeof DiscoverRoute
  InvestorFeedRoute: typeof InvestorFeedRoute
  MatchesRoute: typeof MatchesRoute
  OnboardingRoute: typeof OnboardingRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
  ForumPostIdRoute: typeof ForumPostIdRoute
  InboxConversationIdRoute: typeof InboxConversationIdRoute
  ProfileFounderIdRoute: typeof ProfileFounderIdRoute
  ProfileMeRoute: typeof ProfileMeRoute
  ForumIndexRoute: typeof ForumIndexRoute
  InboxIndexRoute: typeof InboxIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches': {
      id: '/matches'
      path: '/matches'
      fullPath: '/matches'
      preLoaderRoute: typeof MatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investor-feed': {
      id: '/investor-feed'
      path: '/investor-feed'
      fullPath: '/investor-feed'
      preLoaderRoute: typeof InvestorFeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox/': {
      id: '/inbox/'
      path: '/inbox'
      fullPath: '/inbox/'
      preLoaderRoute: typeof InboxIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forum/': {
      id: '/forum/'
      path: '/forum'
      fullPath: '/forum/'
      preLoaderRoute: typeof ForumIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/me': {
      id: '/profile/me'
      path: '/profile/me'
      fullPath: '/profile/me'
      preLoaderRoute: typeof ProfileMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$founderId': {
      id: '/profile/$founderId'
      path: '/profile/$founderId'
      fullPath: '/profile/$founderId'
      preLoaderRoute: typeof ProfileFounderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox/$conversationId': {
      id: '/inbox/$conversationId'
      path: '/inbox/$conversationId'
      fullPath: '/inbox/$conversationId'
      preLoaderRoute: typeof InboxConversationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forum/$postId': {
      id: '/forum/$postId'
      path: '/forum/$postId'
      fullPath: '/forum/$postId'
      preLoaderRoute: typeof ForumPostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  DiscoverRoute: DiscoverRoute,
  InvestorFeedRoute: InvestorFeedRoute,
  MatchesRoute: MatchesRoute,
  OnboardingRoute: OnboardingRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
  ForumPostIdRoute: ForumPostIdRoute,
  InboxConversationIdRoute: InboxConversationIdRoute,
  ProfileFounderIdRoute: ProfileFounderIdRoute,
  ProfileMeRoute: ProfileMeRoute,
  ForumIndexRoute: ForumIndexRoute,
  InboxIndexRoute: InboxIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
